import type { Metadata } from 'next';
import { Inter, Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import FilePickerContainer from '@/components/fileHandler/FilePickerContainer';

const inter = Inter({ subsets: ['latin'] });
const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body
        className={`${plusJakarta.className} text-theme-fontDark font-normal`}
      >
        <Header />

        <main className='relative'>
          <div className='h-1/4 bg-theme-lightGray w-full flex gap-12 flex-col justify-center items-center py-44'>
            <FilePickerContainer />
          </div>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
